// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: pkg/proto/signaling.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_OFFER     MessageType = 0
	MessageType_ANSWER    MessageType = 1
	MessageType_CANDIDATE MessageType = 2
	MessageType_LEAVE     MessageType = 3
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "OFFER",
		1: "ANSWER",
		2: "CANDIDATE",
		3: "LEAVE",
	}
	MessageType_value = map[string]int32{
		"OFFER":     0,
		"ANSWER":    1,
		"CANDIDATE": 2,
		"LEAVE":     3,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_signaling_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_pkg_proto_signaling_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_signaling_proto_rawDescGZIP(), []int{0}
}

type SignalMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=signaling.MessageType" json:"type,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	MemberId      string                 `protobuf:"bytes,3,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Sdp           *string                `protobuf:"bytes,4,opt,name=sdp,proto3,oneof" json:"sdp,omitempty"`
	Candidate     *ICECandidate          `protobuf:"bytes,5,opt,name=candidate,proto3,oneof" json:"candidate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalMessage) Reset() {
	*x = SignalMessage{}
	mi := &file_pkg_proto_signaling_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalMessage) ProtoMessage() {}

func (x *SignalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_signaling_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalMessage.ProtoReflect.Descriptor instead.
func (*SignalMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_signaling_proto_rawDescGZIP(), []int{0}
}

func (x *SignalMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_OFFER
}

func (x *SignalMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SignalMessage) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *SignalMessage) GetSdp() string {
	if x != nil && x.Sdp != nil {
		return *x.Sdp
	}
	return ""
}

func (x *SignalMessage) GetCandidate() *ICECandidate {
	if x != nil {
		return x.Candidate
	}
	return nil
}

type ICECandidate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Candidate        string                 `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	SdpMid           *string                `protobuf:"bytes,2,opt,name=sdp_mid,json=sdpMid,proto3,oneof" json:"sdp_mid,omitempty"`
	SdpMlineIndex    *uint32                `protobuf:"varint,3,opt,name=sdp_mline_index,json=sdpMlineIndex,proto3,oneof" json:"sdp_mline_index,omitempty"`
	UsernameFragment *string                `protobuf:"bytes,4,opt,name=username_fragment,json=usernameFragment,proto3,oneof" json:"username_fragment,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ICECandidate) Reset() {
	*x = ICECandidate{}
	mi := &file_pkg_proto_signaling_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICECandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICECandidate) ProtoMessage() {}

func (x *ICECandidate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_signaling_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICECandidate.ProtoReflect.Descriptor instead.
func (*ICECandidate) Descriptor() ([]byte, []int) {
	return file_pkg_proto_signaling_proto_rawDescGZIP(), []int{1}
}

func (x *ICECandidate) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *ICECandidate) GetSdpMid() string {
	if x != nil && x.SdpMid != nil {
		return *x.SdpMid
	}
	return ""
}

func (x *ICECandidate) GetSdpMlineIndex() uint32 {
	if x != nil && x.SdpMlineIndex != nil {
		return *x.SdpMlineIndex
	}
	return 0
}

func (x *ICECandidate) GetUsernameFragment() string {
	if x != nil && x.UsernameFragment != nil {
		return *x.UsernameFragment
	}
	return ""
}

var File_pkg_proto_signaling_proto protoreflect.FileDescriptor

const file_pkg_proto_signaling_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/proto/signaling.proto\x12\tsignaling\"\xda\x01\n" +
	"\rSignalMessage\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.signaling.MessageTypeR\x04type\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tmember_id\x18\x03 \x01(\tR\bmemberId\x12\x15\n" +
	"\x03sdp\x18\x04 \x01(\tH\x00R\x03sdp\x88\x01\x01\x12:\n" +
	"\tcandidate\x18\x05 \x01(\v2\x17.signaling.ICECandidateH\x01R\tcandidate\x88\x01\x01B\x06\n" +
	"\x04_sdpB\f\n" +
	"\n" +
	"_candidate\"\xdf\x01\n" +
	"\fICECandidate\x12\x1c\n" +
	"\tcandidate\x18\x01 \x01(\tR\tcandidate\x12\x1c\n" +
	"\asdp_mid\x18\x02 \x01(\tH\x00R\x06sdpMid\x88\x01\x01\x12+\n" +
	"\x0fsdp_mline_index\x18\x03 \x01(\rH\x01R\rsdpMlineIndex\x88\x01\x01\x120\n" +
	"\x11username_fragment\x18\x04 \x01(\tH\x02R\x10usernameFragment\x88\x01\x01B\n" +
	"\n" +
	"\b_sdp_midB\x12\n" +
	"\x10_sdp_mline_indexB\x14\n" +
	"\x12_username_fragment*>\n" +
	"\vMessageType\x12\t\n" +
	"\x05OFFER\x10\x00\x12\n" +
	"\n" +
	"\x06ANSWER\x10\x01\x12\r\n" +
	"\tCANDIDATE\x10\x02\x12\t\n" +
	"\x05LEAVE\x10\x032N\n" +
	"\tSignaling\x12A\n" +
	"\aConnect\x12\x18.signaling.SignalMessage\x1a\x18.signaling.SignalMessage(\x010\x01B\vZ\tpkg/pb;pbb\x06proto3"

var (
	file_pkg_proto_signaling_proto_rawDescOnce sync.Once
	file_pkg_proto_signaling_proto_rawDescData []byte
)

func file_pkg_proto_signaling_proto_rawDescGZIP() []byte {
	file_pkg_proto_signaling_proto_rawDescOnce.Do(func() {
		file_pkg_proto_signaling_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_signaling_proto_rawDesc), len(file_pkg_proto_signaling_proto_rawDesc)))
	})
	return file_pkg_proto_signaling_proto_rawDescData
}

var file_pkg_proto_signaling_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_signaling_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_signaling_proto_goTypes = []any{
	(MessageType)(0),      // 0: signaling.MessageType
	(*SignalMessage)(nil), // 1: signaling.SignalMessage
	(*ICECandidate)(nil),  // 2: signaling.ICECandidate
}
var file_pkg_proto_signaling_proto_depIdxs = []int32{
	0, // 0: signaling.SignalMessage.type:type_name -> signaling.MessageType
	2, // 1: signaling.SignalMessage.candidate:type_name -> signaling.ICECandidate
	1, // 2: signaling.Signaling.Connect:input_type -> signaling.SignalMessage
	1, // 3: signaling.Signaling.Connect:output_type -> signaling.SignalMessage
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_signaling_proto_init() }
func file_pkg_proto_signaling_proto_init() {
	if File_pkg_proto_signaling_proto != nil {
		return
	}
	file_pkg_proto_signaling_proto_msgTypes[0].OneofWrappers = []any{}
	file_pkg_proto_signaling_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_signaling_proto_rawDesc), len(file_pkg_proto_signaling_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_signaling_proto_goTypes,
		DependencyIndexes: file_pkg_proto_signaling_proto_depIdxs,
		EnumInfos:         file_pkg_proto_signaling_proto_enumTypes,
		MessageInfos:      file_pkg_proto_signaling_proto_msgTypes,
	}.Build()
	File_pkg_proto_signaling_proto = out.File
	file_pkg_proto_signaling_proto_goTypes = nil
	file_pkg_proto_signaling_proto_depIdxs = nil
}
